"""modif nom table many to many lower case

Revision ID: 1fda4e38ea72
Revises: 21786120e51c
Create Date: 2023-07-25 11:18:26.245375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fda4e38ea72'
down_revision = '21786120e51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Log')
    op.drop_table('like')
    op.drop_table('Signal')
    op.drop_table('Recipe_ingredient_int')
    with op.batch_alter_table('img', schema=None) as batch_op:
        batch_op.drop_index('link_img')

    op.drop_table('img')
    op.drop_table('comment')
    op.drop_table('post')
    op.drop_table('recipe')
    op.drop_table('history')
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_index('id_user')

    op.drop_table('friend')
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index('name_ingredient')

    op.drop_table('ingredient')
    
    op.drop_table('notif')
    # ### end Alembic commands ###
    
    op.create_table('notif',
    sa.Column('id_notif', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creation_date_notif', mysql.DATETIME(), nullable=False),
    sa.Column('id_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_recipe', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_post', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_like', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_notif'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Log',
    sa.Column('id_user_0', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_user_1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_recipe', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_post', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_com', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_ingredient', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_notifi', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_history', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_like', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_log', mysql.DATETIME(), nullable=False),
    sa.Column('crud', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_com'], ['comment.id_com'], name='log_ibfk_5'),
    sa.ForeignKeyConstraint(['id_history'], ['history.id_history'], name='log_ibfk_8'),
    sa.ForeignKeyConstraint(['id_ingredient'], ['ingredient.id_ingredient'], name='log_ibfk_6'),
    sa.ForeignKeyConstraint(['id_like'], ['like.id_like'], name='log_ibfk_9'),
    sa.ForeignKeyConstraint(['id_notifi'], ['notif.id_notif'], name='log_ibfk_7'),
    sa.ForeignKeyConstraint(['id_post'], ['post.id_post'], name='log_ibfk_4'),
    sa.ForeignKeyConstraint(['id_recipe'], ['recipe.id_recipe'], name='log_ibfk_3'),
    sa.ForeignKeyConstraint(['id_user_0'], ['user.id_user'], name='log_ibfk_1'),
    sa.ForeignKeyConstraint(['id_user_1'], ['user.id_user'], name='log_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ingredient',
    sa.Column('id_ingredient', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_ingredient', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id_ingredient'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_index('name_ingredient', ['name_ingredient'], unique=False)

    op.create_table('friend',
    sa.Column('id_friend', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('list_friends', mysql.JSON(), nullable=True),
    sa.Column('id_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_friend'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.create_index('id_user', ['id_user'], unique=False)

    op.create_table('history',
    sa.Column('id_history', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('search', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_history'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recipe',
    sa.Column('id_recipe', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_recipe', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('intro', mysql.TEXT(), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('type_recipe', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diet', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('creation_date_recipe', mysql.DATETIME(), nullable=False),
    sa.Column('modification_date_recipe', mysql.DATETIME(), nullable=True),
    sa.Column('statut', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('view', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_recipe'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Signal',
    sa.Column('id_user_signaling', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_user_signaled', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_recipe', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_post', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_com', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_img', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creation_date_signal', mysql.DATETIME(), nullable=False),
    sa.Column('content_signal', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_com'], ['comment.id_com'], name='signal_ibfk_5'),
    sa.ForeignKeyConstraint(['id_img'], ['img.id_img'], name='signal_ibfk_6'),
    sa.ForeignKeyConstraint(['id_post'], ['post.id_post'], name='signal_ibfk_4'),
    sa.ForeignKeyConstraint(['id_recipe'], ['recipe.id_recipe'], name='signal_ibfk_3'),
    sa.ForeignKeyConstraint(['id_user_signaled'], ['user.id_user'], name='signal_ibfk_2'),
    sa.ForeignKeyConstraint(['id_user_signaling'], ['user.id_user'], name='signal_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('post',
    sa.Column('id_post', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_post', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('content_post', mysql.TEXT(), nullable=False),
    sa.Column('creation_date_post', mysql.DATETIME(), nullable=False),
    sa.Column('modification_date_post', mysql.DATETIME(), nullable=True),
    sa.Column('view', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_post'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comment',
    sa.Column('id_com', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_com', mysql.VARCHAR(length=2048), nullable=False),
    sa.Column('creation_date_comment', mysql.DATETIME(), nullable=False),
    sa.Column('modification_date_comment', mysql.DATETIME(), nullable=True),
    sa.Column('id_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_recipe', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_post', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_com'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('img',
    sa.Column('id_img', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_img', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('caption_img', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('link_img', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('id_user', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_recipe', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_post', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_img'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('img', schema=None) as batch_op:
        batch_op.create_index('link_img', ['link_img'], unique=False)

    op.create_table('Recipe_ingredient_int',
    sa.Column('id_recipe', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_ingredient', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_ingredient'], ['ingredient.id_ingredient'], name='recipe_ingredient_int_ibfk_2'),
    sa.ForeignKeyConstraint(['id_recipe'], ['recipe.id_recipe'], name='recipe_ingredient_int_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('like',
    sa.Column('id_like', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_recipe', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_post', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_com', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_like'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
